name: Android ADB

on:
  workflow_dispatch:

jobs:
  adb:
    runs-on: [self-hosted, macOS]

    steps:
      - name: Show runner info
        run: |
          uname -a
          whoami

      - name: Check ADB
        run: |
          adb version
          adb devices -l

      - name: Show device model
        run: |
          adb shell getprop ro.product.model

      - name: Show Android version
        run: |
          adb shell getprop ro.build.version.release
